### ISSUE TITLE
Public Link

### ISSUE THREAD

**Issue by rondagdag** [mrcity/mlworkshop#1]
great instructions, easy to follow.
I got thru the end and it didn't load the image. Researched it a little bit more and found out that when you upload the images, make sure to click the "Public Link" checkbox, this will load the image correctly. Please add to the instructions.
Thanks,
Ron Dagdag

**Comment by mrcity** [comment]
Glad you enjoyed the instructions, Ron! Thanks for suggesting the improvement.
